auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: zefengchow
url: http://zefengchow.github.io/
feed: /atom.xml
author_info: <a href="hhttp://zefengchow.github.io//">Aremo</a>
